### ISSUE TITLE
Investigate using sshuttle as a service

### ISSUE THREAD

**Issue by iamkirkbater** [openshift/ocm-container#75]
I just noticed as I was trying to fix sshuttle on my mac that there's a blog post at the bottom of the github page that shows how to run sshuttle as a service.

The main benefit I see here is the keepalive, which is just really annoying when I'm trying to do something, get distracted or get a cup of coffee, and come back and have to `kill $(cat sshuttle.pid)` and set up the tunnel again to get into a new cluster.

https://perfecto25.medium.com/using-sshuttle-as-a-service-bec2684a65fe

**Comment by georgettica** [comment]
what about running the sshuttle with the commands suggested?

```ocm-backplane tunnel <CLUSTERID> -- --ssh-cmd 'ssh -o ServerAliveInterval=60' --no-latency-control &```

**Comment by clcollins** [comment]
/unfreeze

Is that a command?

Let's either work on something or let it age out.  Perpetual frozen issues with no progress are no help.

**Comment by clcollins** [comment]
/remove-lifecycle frozen

If this doesn't work, I will RTFM and stop spamming everyone

**Comment by iamkirkbater** [comment]
Closing this because we no longer need tunnels.
