### ISSUE TITLE
possible solution for rhash fix

### ISSUE THREAD

**Issue by georgettica** [openshift/ocm-container#83]
https://github.com/openshift/ocm-container/blob/f1c5161214c4d4bdaf8c51ccf543c7fafa29133e/Dockerfile#L135-L136

I found that we can 
```
rhash -c <( grep ^yq_linux_amd64\   checksums  ) --printf "" -m "" --skip-ok -a
```
which returns:
```
--( Verifying ${TMP_FILENAME} )------------------------------------------------------
--------------------------------------------------------------------------------
Everything OK
RHash: skipping: (message)
```

so we can `grep ^Everything OK$`
@clcollins WDYT? (can wait for whenever you get to this)

I am thinking on solutions for the other cli's (so we don't need to `--ignore-missing`

**Comment by georgettica** [comment]
A release has been cut, hopefully this will be fixed in ocm-container

**Comment by clcollins** [comment]
@georgettica Not sure I fully understand your last comment or why this was re-opened?  Looks like the install is in line with the way the other installs are done now?

**Comment by georgettica** [comment]
The new release of rhash can make this line I added shorter, there is a linked issue for it

**Comment by georgettica** [comment]
/close
:(
