### ISSUE TITLE
use a different way of builing the oc binaries

### ISSUE THREAD

**Issue by georgettica** [openshift/ocm-container#85]
I just saw https://github.com/openshift-kni/cnf-features-deploy/blob/master/cnf-tests/Dockerfile
where they pull the binary from an official docker image

https://github.com/openshift/ocm-container/blob/f1c5161214c4d4bdaf8c51ccf543c7fafa29133e/Dockerfile#L68-L77

**Comment by georgettica** [comment]
/lifecycle frozen
unfreeze when you can do somethin on this

**Comment by clcollins** [comment]
There doesn't appear to be appetite to implement this way of grabbing the oc binary.  The issue is a year old with no takers, so I'm going to close it.
